####
####
# Study consequences of model misspecification in non-parametric models
# this is for a constant mortality, constant germination model
# when the data is generated by an age-dependent mortality, constant germination model
# NOTE: this script was used to analyze misspecification for multiple 'true' germination
# values, which produced Figure 3 in the re-submission
# I.E. Script produces Figure 3, main text
####
####

# - Libraries ----
library(MCMCvis)
library(tidyverse)
source("scripts/005_estimability/01_functionsEstimability.R")

# - Functions ----

# - +Generate table of parameters from simulation filenames ----
f = function(x){
  tmp=strsplit(x,"-")[[1]]
  n.bags=as.numeric(tmp[2])
  p.m=as.numeric(tmp[3])
  p.g=as.numeric(sub(".RDS","",tmp[4]))
  obj=c(n.bags=n.bags,p.m=p.m,p.g=p.g)
  return(obj)
}

# - +Extract posterior----
f.extract = function(file=x,params=c("lambda")){
  samples.rjags = readRDS(file);
  mat <- MCMCchains(samples.rjags,params=params);
  return(mat)
}

# - Germination ----
focalParam = "p.g"

# - Extract posteriors ----

# get names of directories
tempDirs=list.dirs("outputs/002_statisticalModelFitting/03_misspecification",recursive=FALSE)

# construct parameter table from file names
parm.table=data.frame(do.call(rbind,lapply(tempDirs,f)))

# list to hold evaluation output
eval.list = list()

# list for point estimates
pm.bags = list()
pm.addition = list()

# - For loop to evaluate models ----

for(i in 1:dim(parm.table)[1]){
  
  # - +Extract posteriors ----
  
  # get current directory
  tmp = tempDirs[i]
  parm.table.tmp = parm.table[i,]
  
  # get filenames in directories
  fileNamesBags=list.files(paste0(tmp,"/posteriors-NpCmCg/seedBagBurial/"))
  fileNamesAddition=list.files(paste0(tmp,"/posteriors-NpCmCg/seedAddition/"))
  
  # list of all file paths for all posteriors
  fitsBags = paste0(paste0(tmp,"/posteriors-NpCmCg/seedBagBurial/",fileNamesBags))
  fitsAddition = paste0(paste0(tmp,"/posteriors-NpCmCg/seedAddition/",fileNamesAddition))
  
  # if directory is empty (no files), go to next one
  if(length(fitsBags)<1) next
  
  # extract posteriors for mortality and germination
  posterior.bags.all = lapply(fitsBags,f.extract,params=c("p.m","p.g"))
  posterior.addition.all = lapply(fitsAddition,f.extract,params=c("p.m","p.g"))
  
  pm.bags[[i]]=unlist(lapply(posterior.bags.all,function(x) quantile(x[,1],c(.025,.5,.975))))
  pm.addition[[i]]=unlist(lapply(posterior.addition.all,function(x) quantile(x[,1],c(.025,.5,.975))))
  
  # - +Model assessment ----
  
  eval.bags = wrapper.fun(posterior.list = posterior.bags.all, par = focalParam, parm.df = parm.table.tmp)
  eval.addition = wrapper.fun(posterior.list = posterior.addition.all, par = focalParam, parm.df = parm.table.tmp)
  
  # add experiment variable
  eval.out = rbind(data.frame(c(eval.bags,experiment="bags")),data.frame(c(eval.addition,experiment="addition")))
  
  # put in list
  eval.list[[i]] = eval.out
  
}

# - Bind data frame ----

df = do.call("rbind", eval.list)

# - Mortality ----
focalParam = "p.m"

# - Extract posteriors ----

# get names of directories
tempDirs=list.dirs("outputs/002_statisticalModelFitting/03_misspecification",recursive=FALSE)

# construct parameter table from file names
parm.table=data.frame(do.call(rbind,lapply(tempDirs,f)))

# list to hold evaluation output
eval.list = list()

# list for point estimates
pm.bags = list()
pm.addition = list()

# - For loop to evaluate models ----
pm.vec = c(0.1,0.2,0.3)

parm.table = rbind(parm.table,parm.table,parm.table)
parm.table$p.m[1:30] = 0.1
parm.table$p.m[31:60] = 0.2
parm.table$p.m[61:90] = 0.3

index.vec=rep(1:30,3)

for(i in 1:dim(parm.table)[1]){
  
  # - +Extract posteriors ----
  
  # get current directory
  tmp = tempDirs[index.vec[i]]
  parm.table.tmp = parm.table[i,]
  
  # get filenames in directories
  fileNamesBags=list.files(paste0(tmp,"/posteriors-NpCmCg/seedBagBurial/"))
  fileNamesAddition=list.files(paste0(tmp,"/posteriors-NpCmCg/seedAddition/"))
  
  # list of all file paths for all posteriors
  fitsBags = paste0(paste0(tmp,"/posteriors-NpCmCg/seedBagBurial/",fileNamesBags))
  fitsAddition = paste0(paste0(tmp,"/posteriors-NpCmCg/seedAddition/",fileNamesAddition))
  
  # if directory is empty (no files), go to next one
  if(length(fitsBags)<1) next
  
  # extract posteriors for mortality and germination
  posterior.bags.all = lapply(fitsBags,f.extract,params=c("p.m","p.g"))
  posterior.addition.all = lapply(fitsAddition,f.extract,params=c("p.m","p.g"))
  
  pm.bags[[i]]=unlist(lapply(posterior.bags.all,function(x) quantile(x[,1],c(.025,.5,.975))))
  pm.addition[[i]]=unlist(lapply(posterior.addition.all,function(x) quantile(x[,1],c(.025,.5,.975))))
  
  # - +Model assessment ----
  
  eval.bags = wrapper.fun(posterior.list = posterior.bags.all, par = focalParam, parm.df = parm.table.tmp)
  eval.addition = wrapper.fun(posterior.list = posterior.addition.all, par = focalParam, parm.df = parm.table.tmp)
  
  # add experiment variable
  eval.out = rbind(data.frame(c(eval.bags,experiment="bags")),data.frame(c(eval.addition,experiment="addition")))
  
  # put in list
  eval.list[[i]] = eval.out
  
}

# - Bind data frame ----

df.pm = do.call("rbind", eval.list)

# - Main text plot ----

# set font sizes
pt12 = 1
pt10 = 10/12
pt9 = 9/12
pt8 = 8/12
pt7 = 7/12


# germination values
germination.vec = c(0.1, 0.2, 0.3, 0.4, 0.5)

df.pg.all = df
df.pm.all = df.pm

# select p[g] = 0.1
df = df.pg.all[df.pg.all$p.g==germination.vec[1],]
df.pm = df.pm.all[df.pm.all$p.g==germination.vec[1],]

# - +Bias ----

panels.pg <- unique(df[,c("p.m","p.g")])
panels.pm <- unique(df.pm[,c("p.m","p.g")])

tiff(filename=paste0("products/figures/summary-misspecification-maintext.tif"),
     height=7,width=6,units="in",res=300,compression="lzw",pointsize=12)

panelLabs=c("A.","B.","C.","D.")

par(mfrow = c(4,4),
    oma = c(2.5,4,0,0) + 0.1,
    mar = c(1,0,1,1) + 0.1)

# - ++ Mortality ----

for(i in 1:dim(panels.pm)[1]){

  # get data for panel
  df.tmp <- df.pm.all %>%
    dplyr::filter(p.m==panels.pm$p.m[i]) %>%
    dplyr::filter(n.bags==30)

  if(focalParam=="p.m"){yax = .02}else{yax = 0}
  plot(NA,
       xlim=c(0,.55), ylim = c(-.2, .2),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=FALSE)
  if(i==1){ axis(2, at = seq(-.2,.2, by = .05), labels = F);
    axis(2, at = seq(-.2, .2, by = .1), las=1, cex = pt7) }
  
  abline(h = 0, col = "gray50")
  box()
  
  segments(x0=df.tmp$p.g + c(-.01,.01),
           y0=df.tmp$bias.mean-df.tmp$bias.ci95,
           y1=df.tmp$bias.mean+df.tmp$bias.ci95)
  points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$bias.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  if(i==1){ mtext(side=3, line =0,expression(p[m1] ), cex = pt9 , adj = .5)}
  if(i==2){ mtext(side=3, line =0,expression(p[m2] ), cex = pt9 , adj = .5)}
  if(i==3){ mtext(side=3, line =0,expression(p[m3] ), cex = pt9 , adj = .5)}
  
  
  if(i==1){
    mtext(side=2, line = 2.7, "Bias", cex = pt9)
  }

}

# - ++ Germination ----

# get data for panel
df.tmp <- df.pg.all %>% 
  dplyr::filter(p.m==panels.pg$p.m )%>%
  dplyr::filter(n.bags==30)

if(focalParam=="p.g"){yax = .02}else{yax = 0}
plot(NA,
     xlim=c(0,.55), ylim = c(-.2, .2),
     ylab='',
     xlab="",
     yaxt='n',
     xaxt='n')
axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=F)

abline(h = 0, col = "gray50")
box()

segments(x0=df.tmp$p.g + c(-.01,.01),
         y0=df.tmp$bias.mean-df.tmp$bias.ci95,
         y1=df.tmp$bias.mean+df.tmp$bias.ci95)
points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$bias.mean ,
       pch=ifelse(df.tmp$experiment=="bags",21,21),
       bg=ifelse(df.tmp$experiment=="bags","black","white"))

mtext(side=3, line =0,paste0(panelLabs[4]), cex = pt8 , adj = 0)
mtext(side=3, line =0,expression(p[g] ), cex = pt9 , adj = .5)


# - +Width ----

panelLabs = c("E.","F.","G.","H.")

# - ++ Mortality ----

for(i in 1:dim(panels.pm)[1]){
  
  # get data for panel
  df.tmp <- df.pm.all %>%
    dplyr::filter(p.m==panels.pm$p.m[i]) %>%
    dplyr::filter(n.bags==30)
  
  if(focalParam=="p.m"){yax = .2}else{yax = 0}

  plot(NA,
       xlim=c(0,.55), ylim = c(0, .2),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=F)
  if(i==1){ axis(2, at = seq(0,.2, by = .05), labels = F);
    axis(2, at = seq(0, .2, by = .1), las=1, cex = pt7) }
  
  abline(h = 0, col = "gray50")
  box()
  
  segments(x0=df.tmp$p.g + c(-.01,.01),
           y0=df.tmp$width.mean-df.tmp$width.ci95,
           y1=df.tmp$width.mean+df.tmp$width.ci95)
  points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$width.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  
  if(i==1){
    mtext(side=2, line = 2.5, "95% credible interval width", cex = pt9)
  }
  
}

# - ++ Germination ----

# get data for panel
df.tmp <- df.pg.all %>% 
  dplyr::filter(p.m==panels.pg$p.m )%>%
  dplyr::filter(n.bags==30)

if(focalParam=="p.g"){yax = .02}else{yax = 0}
plot(NA,
     xlim=c(0,.55), ylim = c(0, .2),
     ylab='',
     xlab="",
     yaxt='n',
     xaxt='n')
axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=F)
if(i==1){  axis(2, at = seq(0, .2+yax, by = .05), labels=F )}

abline(h = 0, col = "gray50")
box()

segments(x0=df.tmp$p.g + c(-.01,.01),
         y0=df.tmp$width.mean-df.tmp$width.ci95,
         y1=df.tmp$width.mean+df.tmp$width.ci95)
points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$width.mean ,
       pch=ifelse(df.tmp$experiment=="bags",21,21),
       bg=ifelse(df.tmp$experiment=="bags","black","white"))

mtext(side=3, line =0,paste0(panelLabs[4]), cex = pt8 , adj = 0)


# - +Bias ----

panelLabs=c("I.","J.","K.","L.")

# - ++ Mortality ----

for(i in 1:dim(panels.pm)[1]){
  
  # get data for panel
  df.tmp <- df.pm.all %>%
    dplyr::filter(p.m==panels.pm$p.m[i]) %>%
    dplyr::filter(n.bags==30)
  
  if(focalParam=="p.m"){yax = .02}else{yax = 0}
  plot(NA,
       xlim=c(0,.55), ylim = c(0, 1),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=FALSE)
  if(i==1){ axis(2, at = seq(0,1, by = .1), labels = F);
    axis(2, at = seq(0, 1, by = .2), las=1, cex = pt7) }
  
  abline(h = .95, col = "gray50")
  box()
  
  segments(x0=df.tmp$p.g + c(-.01,.01),
           y0=df.tmp$coverage.lo,
           y1=df.tmp$coverage.hi)
  points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$coverage.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  
  if(i==1){
    mtext(side=2, line = 2.7, "Coverage", cex = pt9)
  }
  
}

# - ++ Germination ----

# get data for panel
df.tmp <- df.pg.all %>% 
  dplyr::filter(p.m==panels.pg$p.m )%>%
  dplyr::filter(n.bags==30)

if(focalParam=="p.m"){yax = .02}else{yax = 0}
plot(NA,
     xlim=c(0,.55), ylim = c(0, 1),
     ylab='',
     xlab="",
     yaxt='n',
     xaxt='n')
axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=FALSE)
if(i==1){ axis(2, at = seq(0,1, by = .1), labels = F);
  axis(2, at = seq(0, 1, by = .2), las=1, cex = pt7) }

abline(h = .95, col = "gray50")
box()

segments(x0=df.tmp$p.g + c(-.01,.01),
         y0=df.tmp$coverage.lo,
         y1=df.tmp$coverage.hi)
points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$coverage.mean ,
       pch=ifelse(df.tmp$experiment=="bags",21,21),
       bg=ifelse(df.tmp$experiment=="bags","black","white"))

mtext(side=3, line =0,paste0(panelLabs[4]), cex = pt8 , adj = 0)

# - +Width ----

panelLabs = c("M.","N.","O.","P.")

# - ++ Mortality ----

for(i in 1:dim(panels.pm)[1]){
  
  # get data for panel
  df.tmp <- df.pm.all %>%
    dplyr::filter(p.m==panels.pm$p.m[i]) %>%
    dplyr::filter(n.bags==30)
  
  if(focalParam=="p.m"){yax = .2}else{yax = 0}
  
  plot(NA,
       xlim=c(0,.55), ylim = c(0,.2),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=TRUE)
  if(i==1){ axis(2, at = seq(0,.2, by = .05), labels = F);
    axis(2, at = seq(0,.2, by = .1), las=1, cex = pt7) }
  
  abline(h = 0, col = "gray50")
  box()

  points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$rmse ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  
  if(i==1){
    mtext(side=2, line = 2.5, "RMSE", cex = pt9)
  }
  
}

# - ++ Germination ----

# get data for panel
df.tmp <- df.pg.all %>% 
  dplyr::filter(p.m==panels.pg$p.m )%>%
  dplyr::filter(n.bags==30)

if(focalParam=="p.g"){yax = .02}else{yax = 0}
plot(NA,
     xlim=c(0,.55), ylim = c(0, .2),
     ylab='',
     xlab="",
     yaxt='n',
     xaxt='n')
axis(1, at = seq(0 , .5, by = .1), las=1, cex = pt7,labels=TRUE)
if(i==1){  axis(2, at = seq(0, .2+yax, by = .05), labels=F )}

abline(h = 0, col = "gray50")
box()

points(x= df.tmp$p.g + c(-.01,.01), y = df.tmp$rmse ,
       pch=ifelse(df.tmp$experiment=="bags",21,21),
       bg=ifelse(df.tmp$experiment=="bags","black","white"))

mtext(side=3, line =0,paste0(panelLabs[4]), cex = pt8 , adj = 0)

mtext(side=1, line = 1.1, expression("True probability of germination, "~p[g]), cex = pt9,  outer = TRUE)

dev.off()


