####
####
# Study consequences of model overspecification in non-parametric models
# this is for a age-dependent mortality, constant germination model
# when the data is generated by a constant mortality, constant germination model
####
####

# - Libraries ----
library(MCMCvis)
library(tidyverse)
source("scripts/007_overspecification/01_functionsOverspecification.R")

# - Functions ----

# - +Generate table of parameters from simulation filenames ----
f = function(x){
  tmp=strsplit(x,"-")[[1]]
  n.bags=as.numeric(tmp[2])
  p.m=as.numeric(tmp[3])
  p.g=as.numeric(sub(".RDS","",tmp[4]))
  obj=c(n.bags=n.bags,p.m=p.m,p.g=p.g)
  return(obj)
}

# - +Extract posterior----
f.extract = function(file=x,params=c("lambda")){
  samples.rjags = readRDS(file);
  mat <- MCMCchains(samples.rjags,params=params);
  return(mat)
}

# - Germination ----
focalParam = "p.g"

# - Extract posteriors ----

# get names of directories
tempDirs=list.dirs("outputs/002_statisticalModelFitting/04_overspecification",recursive=FALSE)

# construct parameter table from file names
parm.table=data.frame(do.call(rbind,lapply(tempDirs,f)))

# list to hold evaluation output
eval.list = list()

# list for point estimates
pm.bags = list()
pm.addition = list()

# - For loop to evaluate models ----

for(i in 1:dim(parm.table)[1]){
  
  # - +Extract posteriors ----
  
  # get current directory
  tmp = tempDirs[i]
  parm.table.tmp = parm.table[i,]
  
  # get filenames in directories
  fileNamesBags=list.files(paste0(tmp,"/posteriors-NpVmCg/seedBagBurial/"))
  fileNamesAddition=list.files(paste0(tmp,"/posteriors-NpVmCg/seedAddition/"))
  
  # list of all file paths for all posteriors
  fitsBags = paste0(paste0(tmp,"/posteriors-NpVmCg/seedBagBurial/",fileNamesBags))
  fitsAddition = paste0(paste0(tmp,"/posteriors-NpVmCg/seedAddition/",fileNamesAddition))
  
  # if directory is empty (no files), go to next one
  if(length(fitsBags)<1) next
  
  # extract posteriors for mortality and germination
  posterior.bags.all = lapply(fitsBags,f.extract,params=c("p.m","p.g"))
  posterior.addition.all = lapply(fitsAddition,f.extract,params=c("p.m","p.g"))
  
  pm.bags[[i]]=unlist(lapply(posterior.bags.all,function(x) quantile(x[,1],c(.025,.5,.975))))
  pm.addition[[i]]=unlist(lapply(posterior.addition.all,function(x) quantile(x[,1],c(.025,.5,.975))))
  
  # - +Model assessment ----
  
  eval.bags = wrapper.fun(posterior.list = posterior.bags.all, par = focalParam, parm.df = parm.table.tmp)
  eval.addition = wrapper.fun(posterior.list = posterior.addition.all, par = focalParam, parm.df = parm.table.tmp)
  
  # add experiment variable
  eval.out = rbind(data.frame(c(eval.bags,experiment="bags")),data.frame(c(eval.addition,experiment="addition")))
  
  # put in list
  eval.list[[i]] = eval.out
  
}

# - Bind data frame ----

df = do.call("rbind", eval.list)

# - Mortality ----
focalParamAll = c("p.m[1]","p.m[2]","p.m[3]")

# - Extract posteriors ----

# get names of directories
tempDirs=list.dirs("outputs/002_statisticalModelFitting/04_overspecification",recursive=FALSE)

# construct parameter table from file names
parm.table=data.frame(do.call(rbind,lapply(tempDirs,f)))

# lists to hold evaluation output
eval.list = list()
df.list = list()

# list for point estimates
pm.bags = list()
pm.addition = list()

# - For loop to evaluate models ----

for(h in 1:length(focalParamAll)){
  
  focalParam = focalParamAll[h]
  
  for(i in 1:dim(parm.table)[1]){
    
    # - +Extract posteriors ----
    
    # get current directory
    tmp = tempDirs[i]
    parm.table.tmp = parm.table[i,]
    
    # get filenames in directories
    fileNamesBags=list.files(paste0(tmp,"/posteriors-NpVmCg/seedBagBurial/"))
    fileNamesAddition=list.files(paste0(tmp,"/posteriors-NpVmCg/seedAddition/"))
    
    # list of all file paths for all posteriors
    fitsBags = paste0(paste0(tmp,"/posteriors-NpVmCg/seedBagBurial/",fileNamesBags))
    fitsAddition = paste0(paste0(tmp,"/posteriors-NpVmCg/seedAddition/",fileNamesAddition))
    
    # if directory is empty (no files), go to next one
    if(length(fitsBags)<1) next
    
    # extract posteriors for mortality and germination
    posterior.bags.all = lapply(fitsBags,f.extract,params=c("p.m","p.g"))
    posterior.addition.all = lapply(fitsAddition,f.extract,params=c("p.m","p.g"))
    
    pm.bags[[i]]=unlist(lapply(posterior.bags.all,function(x) quantile(x[,1],c(.025,.5,.975))))
    pm.addition[[i]]=unlist(lapply(posterior.addition.all,function(x) quantile(x[,1],c(.025,.5,.975))))
    
    # - +Model assessment ----
    
    eval.bags = wrapper.fun(posterior.list = posterior.bags.all, par = focalParam, parm.df = parm.table.tmp)
    eval.addition = wrapper.fun(posterior.list = posterior.addition.all, par = focalParam, parm.df = parm.table.tmp)
    
    # add experiment variable
    eval.out = rbind(data.frame(c(eval.bags,experiment="bags")),data.frame(c(eval.addition,experiment="addition")))
    
    # put in list
    eval.list[[i]] = eval.out
    
  }
  
  # - Bind data frame ----
  
  df.pm = do.call("rbind", eval.list)
  df.pm$param = focalParamAll[h]
  
  df.list[[h]] = df.pm
  
}

# - Bind data frames ----

df.pm = do.call("rbind", df.list)

# - Plot for main text ----

# set font sizes
pt12 = 1
pt10 = 10/12
pt9 = 9/12
pt8 = 8/12
pt7 = 7/12

tiff(filename=paste0("products/figures/summary-overspecification-summary",".tif"),
     height=7,width=6,units="in",res=300,compression="lzw",pointsize=12)


df.pm.all <- df.pm
df.pg.all <- df

df.pm <- df.pm.all %>% dplyr::filter(n.bags==30)
df.pg <- df.pg.all %>% dplyr::filter(n.bags==30)

# - ++Bias ----
focal.par = "p.m"

panels.pg <- unique(df.pg[,c("p.m","p.g")])
panels.pm.all <- unique(df.pm[,c("p.m","p.g","param")])


par(mfrow = c(4,4),
    oma = c(2.5,4,1.1,0) + 0.1,
    mar = c(0.4,0,1,.4) + 0.1)

# - + BIAS ----

# main text
panelLabs =  c("A.","B.","C.","D.")

panels.pm <- panels.pm.all[panels.pm.all$param=="p.m[1]",]

for(i in 1:dim(panels.pm)[1]){
  
  # get data for panel
  df.tmp <- df.pm %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  if(focalParam=="p.m"){yax = .02}else{yax = 0}
  plot(NA,
       xlim=c(.5,4.5), ylim = c(-.4, .4),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , 5, by = 1), las=1, cex = pt7,labels=FALSE)
  if(i==1){ axis(2, at = seq(-.4,.4, by = .1), labels = F);
    axis(2, at = seq(-.4, .4, by = .2), las=1, cex = pt7) }
  
  rect(xleft=3.5,xright=6,ybottom=-5,ytop=5,col='gray95',border='gray95')
  abline(h = 0, col = "gray50")
  box()
  
  segments(x0=rep(1:3,each=2) + c(-0.1,0.1),
           y0=df.tmp$bias.mean-df.tmp$bias.ci95,
           y1=df.tmp$bias.mean+df.tmp$bias.ci95)
  points(x= rep(1:3,each=2) + c(-0.1,0.1), y = df.tmp$bias.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  # add germination
  
  box()
  
  # get data for panel
  df.tmp <- df.pg %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  segments(x0=rep(4,each=2) + c(-0.1,0.1),
           y0=df.tmp$bias.mean-df.tmp$bias.ci95,
           y1=df.tmp$bias.mean+df.tmp$bias.ci95)
  points(x= rep(4,each=2) + c(-0.1,0.1), y = df.tmp$bias.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  if(i==1){ mtext(side=3, line =0,expression(paste(p[m]==0.1, ",  ",  p[g]==0.1)), cex = pt8 , adj = 0.5) }
  if(i==2){ mtext(side=3, line =0,expression(paste(p[m]==0.1, ",  ",  p[g]==0.5)), cex = pt8 , adj = 0.5) }
  if(i==3){ mtext(side=3, line =0,expression(paste(p[m]==0.5, ",  ",  p[g]==0.1)), cex = pt8 , adj = 0.5) }
  if(i==4){ mtext(side=3, line =0,expression(paste(p[m]==0.5, ",  ",  p[g]==0.5)), cex = pt8 , adj = 0.5) }
  
  if(i==1){
    mtext(side=2, line = 2.7, expression(paste("Bias")), cex = pt9)
  }
  
}

# - + WIDTH ----

# main text
panelLabs =  c("E.","F.","G.","H.")

panels.pm <- panels.pm.all[panels.pm.all$param=="p.m[1]",]

for(i in 1:dim(panels.pm)[1]){
  
  # get data for panel
  df.tmp <- df.pm %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  if(focalParam=="p.m"){yax = .02}else{yax = 0}
  plot(NA,
       xlim=c(.5,4.5), ylim = c(0, 1),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , 5, by = 1), las=1, cex = pt7,labels=FALSE)
  if(i==1){ axis(2, at = seq(0,1, by = .1), labels = F);
    axis(2, at = seq(0, 1, by = .2), las=1, cex = pt7) }
  
  rect(xleft=3.5,xright=6,ybottom=-5,ytop=5,col='gray95',border='gray95')
  abline(h = 0, col = "gray50")
  box()
  
  segments(x0=rep(1:3,each=2) + c(-0.1,0.1),
           y0=df.tmp$width.mean-df.tmp$width.ci95,
           y1=df.tmp$width.mean+df.tmp$width.ci95)
  points(x= rep(1:3,each=2) + c(-0.1,0.1), y = df.tmp$width.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  # add germination
  
  box()
  
  # get data for panel
  df.tmp <- df.pg %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  segments(x0=rep(4,each=2) + c(-0.1,0.1),
           y0=df.tmp$width.mean-df.tmp$width.ci95,
           y1=df.tmp$width.mean+df.tmp$width.ci95)
  points(x= rep(4,each=2) + c(-0.1,0.1), y = df.tmp$width.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  
  if(i==1){
    mtext(side=2, line = 2.7, expression(paste("95% credible interval width")), cex = pt9)
  }
  
}

# - + COVERAGE ----

# main text
panelLabs =  c("I.","J.","K.","L.")

panels.pm <- panels.pm.all[panels.pm.all$param=="p.m[1]",]

for(i in 1:dim(panels.pm)[1]){
  
  # get data for panel
  df.tmp <- df.pm %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  if(focalParam=="p.m"){yax = .02}else{yax = 0}
  plot(NA,
       xlim=c(.5,4.5), ylim = c(.75, 1),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , 5, by = 1), las=1, cex = pt7,labels=FALSE)
  if(i==1){ axis(2, at = seq(.75,1, by = .05), labels = F);
    axis(2, at = seq(.75, 1, by = .1), las=1, cex = pt7) }
  
  rect(xleft=3.5,xright=6,ybottom=-5,ytop=5,col='gray95',border='gray95')
  abline(h = .95, col = "gray50")
  box()
  
  segments(x0=rep(1:3,each=2) + c(-0.1,0.1),
           y0=df.tmp$coverage.lo,
           y1=df.tmp$coverage.hi)
  points(x= rep(1:3,each=2) + c(-0.1,0.1), y = df.tmp$coverage.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  # add germination
  
  box()
  
  # get data for panel
  df.tmp <- df.pg %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  segments(x0=rep(4,each=2) + c(-0.1,0.1),
           y0=df.tmp$coverage.lo,
           y1=df.tmp$coverage.hi)
  points(x= rep(4,each=2) + c(-0.1,0.1), y = df.tmp$coverage.mean ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  
  if(i==1){
    mtext(side=2, line = 2.7, expression(paste("Coverage")), cex = pt9)
  }
  
  
}



# - + RMSE ----

# main text
panelLabs =  c("M.","N.","O.","P.")

panels.pm <- panels.pm.all[panels.pm.all$param=="p.m[1]",]

for(i in 1:dim(panels.pm)[1]){
  
  # get data for panel
  df.tmp <- df.pm %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  if(focalParam=="p.m"){yax = .02}else{yax = 0}
  plot(NA,
       xlim=c(.5,4.5), ylim = c(0, .3),
       ylab='',
       xlab="",
       yaxt='n',
       xaxt='n')
  axis(1, at = seq(0 , 5, by = 1), las=1, cex = pt7,labels=FALSE)
  if(i==1){ axis(2, at = seq(0,.3, by = .05), labels = F);
    axis(2, at = seq(0, .3, by = .1), las=1, cex = pt7) }
  
  rect(xleft=3.5,xright=6,ybottom=-5,ytop=5,col='gray95',border='gray95')
  abline(h = .95, col = "gray50")
  box()
  
  points(x= rep(1:3,each=2) + c(-0.1,0.1), y = df.tmp$rmse ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  # add germination
  
  box()
  
  # get data for panel
  df.tmp <- df.pg %>% 
    dplyr::filter(p.m==panels.pm$p.m[i] & p.g==panels.pm$p.g[i])
  
  
  points(x= rep(4,each=2) + c(-0.1,0.1), y = df.tmp$rmse ,
         pch=ifelse(df.tmp$experiment=="bags",21,21),
         bg=ifelse(df.tmp$experiment=="bags","black","white"))
  
  mtext(side=3, line =0,paste0(panelLabs[i]), cex = pt8 , adj = 0)
  
  if(i==1){
    mtext(side=2, line = 2.7, expression(paste("RMSE")), cex = pt9)
  }
  
  axis(1, at = seq(1 , 4, by = 1), las=1, cex = pt7,
       labels=c(expression(paste(p[m1])),expression(paste(p[m2])),expression(paste(p[m3])),expression(paste(p[g]))))
  
}



dev.off()

